# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.15.0
import pydantic
from typing import Any, Optional


class Author(pydantic.BaseModel):
    id: Any
    name: Any
    bio: Optional[Any]
