# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.15.0
# source: query_sqlite.sql
from typing import Iterator, Optional

import sqlalchemy

from db import models

CREATE_AUTHOR = """-- name: create_author \\:one
INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
)
RETURNING id, name, bio
"""


DELETE_AUTHOR = """-- name: delete_author \\:exec
DELETE FROM authors
WHERE id = ?
"""


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, bio FROM authors
WHERE id = ? LIMIT 1
"""


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio FROM authors
ORDER BY name
"""


UPDATE_AUTHOR = """-- name: update_author \\:exec
UPDATE authors
set name = ?,
bio = ?
WHERE id = ?
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_author(self, *, name: str, bio: Optional[str]) -> Optional[models.Author]:
        # row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), (name, bio)).first()
        # 引数を受け付ける場合、 SQLAlchemy 2.0 までは text を使わないようにする
        row = self._conn.execute(CREATE_AUTHOR, (name, bio)).first()
        if row is None:
            return None
        return models.Author(
            id=row[0],
            name=row[1],
            bio=row[2],
        )

    def delete_author(self, *, id: int) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), (id,))

    def get_author(self, *, id: int) -> Optional[models.Author]:
        # row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), (id,)).first()
        row = self._conn.execute(GET_AUTHOR, (id,)).first()
        if row is None:
            return None
        return models.Author(
            id=row[0],
            name=row[1],
            bio=row[2],
        )

    def list_authors(self) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=row[0],
                name=row[1],
                bio=row[2],
            )

    def update_author(self, *, name: str, bio: Optional[str], id: int) -> None:
        # self._conn.execute(sqlalchemy.text(UPDATE_AUTHOR), (name, bio, id))
        self._conn.execute(UPDATE_AUTHOR, (name, bio, id))
